### ISSUE TITLE
Didn't work with Python 3.10.x

### ISSUE THREAD

**Issue by zsh-is-life** [unexploredtest/neural-networks-and-deep-learning#1]
In a Conda environment with Python 3.10 (On Windows 10 x64):
Running the following command `conda install --file .\requirements.txt --channel conda-forge` resulted in the following UnsatisfiableError:
`
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - scikit-learn==0.24 -> python[version='>=3.6,<3.7.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=3.10
`
Downgrading to python 3.9 fixed this issue.

**Comment by unexploredtest** [comment]
Apparently scikit-learn version 0.24 doesn't support python 3.10. I doubt newer versions of sci-kit learn will break stuff, but will have to test it. In requirements.txt just change `scikit-learn==0.24` to `scikit-learn` so that it downloads the latest version which should support python 3.10.x (Although I have to say I've done no testing yet).

**Comment by unexploredtest** [comment]
Okay scikit learn version 1.0.* supports python 3.10 and doesn't break anything, changing `scikit-learn==0.24` to `scikit-learn < 1.1` should solve the issue
